=== pasccom/QTestLibPlugin/qtestliboutput.dtd
<!ELEMENT qtestliboutput (results+,root|class)>
<!ELEMENT root (class+)>
<!ELEMENT class (function+)>
<!ELEMENT function (row+|message+)>
<!ELEMENT row (message+)>
<!ELEMENT message (text)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT results (unsure+|magicfound+|magicnotfound+)>
<!ELEMENT unsure EMPTY>
<!ELEMENT magicfound EMPTY>
<!ELEMENT magicnotfound EMPTY>

<!ATTLIST results format (all|txt|xml) #REQUIRED>

<!ATTLIST unsure level (silent|normal|verbose1|verbose2|verboses) "normal">
<!ATTLIST magicfound level (silent|normal|verbose1|verbose2|verboses) "normal">
<!ATTLIST magicnotfound level (silent|normal|verbose1|verbose2|verboses) "normal">

<!ATTLIST root type CDATA "Unknown">
<!ATTLIST root id ID #IMPLIED>

<!ATTLIST class name CDATA #REQUIRED>
<!ATTLIST class type CDATA "Unknown">
<!ATTLIST class level (silent|normal|verbose1|verbose2|verboses) "normal">
<!ATTLIST class id ID #IMPLIED>

<!ATTLIST function name CDATA #REQUIRED>
<!ATTLIST function type CDATA "Unknown">
<!ATTLIST function level  CDATA "normal">
<!ATTLIST function id ID #IMPLIED>

<!ATTLIST row title CDATA #REQUIRED>
<!ATTLIST row type CDATA "Unknown">
<!ATTLIST row level (silent|normal|verbose1|verbose2|verboses) "normal">
<!ATTLIST row id ID #IMPLIED>

<!ATTLIST message type CDATA "Unknown">
<!ATTLIST message strict>
<!ATTLIST message level (silent|normal|verbose1|verbose2|verboses) "normal">
<!ATTLIST message format (all|txt|xml) "all">
<!ATTLIST message id ID #IMPLIED>

=== pasccom/QTestLibPlugin/tests/OneSubTest/onesubtest.xml
<?xml version="1.0" ?>
<!-- Copyright 2016-2020 Pascal COMBES <pascom@orange.fr>

     This file is part of QTestLibPlugin.

     QTestLibPlugin is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     QTestLibPlugin is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with QTestLibPlugin. If not, see <http://www.gnu.org/licenses/>
-->

<!DOCTYPE qtestliboutput SYSTEM "../../qtestliboutput.dtd">
<qtestliboutput>
    <results format="xunitxml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
    </results>
    <results format="lightxml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure />
    </results>
    <results format="xml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure />
        <unsure />
    </results>
    <results format="txt">
        <unsure/>
        <magicfound level="silent" />
        <unsure level="verboses" qtmin="5.6.0" />
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="verboses" qtmin="5.12.0" />
        <unsure level="silent" />
        <unsure/>
    </results>
    <class name="OnePassTest" type="Pass" format="!lightxml" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Signal" level="verboses" qtmin="5.6.0">
                 <text strict="false">QThread(29ec6f0) started ()</text>
            </message>
            <message type="Info" level="verbose1" format="txt">
                 <text strict="true">entering</text>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
            </message>
            <message type="Duration" format="xml">
                <text strict="false"> 0.00ms</text>
            </message>
        </function>
        <function name="testPass" type="Pass">
            <message type="Info" level="verbose1" format="txt">
                 <text strict="true">entering</text>
            </message>
            <message type="Info" level="verbose2" file="onepasstest.cpp" line="34">
                 <text strict="true">QVERIFY(true)</text>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
            </message>
            <message type="Duration" format="xml">
                 <text strict="false">0.00ms</text>
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Info" level="verbose1" format="txt">
                 <text strict="true">entering</text>
            </message>
            <message type="Signal" level="verboses" qtmin="5.12.0" format="xunitxml">
                 <text strict="false">QThread(29ec6f0) finished ()</text>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
            </message>
            <message type="Duration" format="xml">
                 <text strict="false">0.00ms</text>
            </message>
        </function>
        <function name="UnknownTestFunc" type="Unknown" level="verboses" qtmin="5.12.0" format="txt">
            <message type="Signal">
                 <text strict="false">QThread(29ec6f0) finished ()</text>
            </message>
        </function>
        <message type="Signal" level="verboses" qtmin="5.12.0" format="xml">
             <text strict="false">QThread(29ec6f0) finished ()</text>
        </message>
        <message type="Duration" format="xml">
             <text strict="false">0.00ms</text>
        </message>
    </class>
    <class name="OneSubTest" type="Pass" format="lightxml" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Signal" level="verboses" qtmin="5.6.0">
                 <text strict="false">QThread(29ec6f0) started ()</text>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
            </message>
            <message type="Duration">
                 <text strict="false">0.00ms</text>
            </message>
        </function>
        <function name="testPass" type="Pass">
            <message type="Info" level="verbose2" file="onepasstest.cpp" line="34">
                 <text strict="true">QVERIFY(true)</text>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
            </message>
            <message type="Duration">
                 <text strict="false">0.00ms</text>
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Pass">
                 <text strict="true">Test passed</text>
            </message>
            <message type="Duration">
                 <text strict="false">0.00ms</text>
            </message>
        </function>
        <message type="Duration">
             <text strict="false">0.00ms</text>
        </message>
    </class>
</qtestliboutput>

=== pasccom/QTestLibPlugin/tests/qt5/OneSubTest/onesubtest.xml
<?xml version="1.0" ?>
<!-- Copyright 2016-2020 Pascal COMBES <pascom@orange.fr>

     This file is part of QTestLibPlugin.

     QTestLibPlugin is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     QTestLibPlugin is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with QTestLibPlugin. If not, see <http://www.gnu.org/licenses/>
-->

<!DOCTYPE qtestliboutput SYSTEM "../../qtestliboutput.dtd">
<qtestliboutput>
    <class name="OnePassTest" type="Pass" format="!lightxml">
        <unsure/>
        <unsure format="xml,xunitxml" />
        <unsure format="xml,xunitxml" />
        <unsure format="xml,xunitxml" />
        <unsure format="xml,xunitxml" />
        <unsure format="xml,xunitxml" />
        <magicfound level="silent" />
        <function name="initTestCase" type="Pass">
            <unsure format="xml" />
            <message type="Signal" level="verboses" qtmin="5.6.0">
                 <text strict="false">QThread(29ec6f0) started ()</text>
                 <unsure/>
                 <unsure format="xml,xunitxml" />
                 <unsure format="xml" />
            </message>
            <message type="Info" level="verbose1" format="txt">
                 <text strict="true">entering</text>
                 <unsure/>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
                 <unsure/>
            </message>
            <message type="Duration" format="xml">
                <text strict="false"> 0.00ms</text>
                <unsure/>
            </message>
            <unsure format="xml" />
        </function>
        <function name="testPass" type="Pass">
            <unsure format="xml" />
            <message type="Info" level="verbose1" format="txt">
                 <text strict="true">entering</text>
                 <unsure/>
            </message>
            <message type="Info" level="verbose2" file="onepasstest.cpp" line="34">
                 <text strict="true">QVERIFY(true)</text>
                 <unsure/>
                 <unsure/>
                 <unsure format="xml" />
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
                 <unsure/>
            </message>
            <message type="Duration" format="xml">
                 <text strict="false">0.00ms</text>
                 <unsure/>
            </message>
            <unsure format="xml" />
        </function>
        <function name="cleanupTestCase" type="Pass">
            <unsure format="xml" />
            <message type="Info" level="verbose1" format="txt">
                 <text strict="true">entering</text>
                 <unsure/>
            </message>
            <message type="Signal" level="verboses" qtmin="5.12.0" format="xunitxml">
                 <text strict="false">QThread(29ec6f0) finished ()</text>
                 <unsure/>
                 <unsure/>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
                 <unsure/>
            </message>
            <message type="Duration" format="xml">
                 <text strict="false">0.00ms</text>
                 <unsure/>
            </message>
            <unsure format="xml" />
        </function>
        <function name="UnknownTestFunc" type="Unknown" level="verboses" format="txt">
            <message type="Signal" qtmin="5.12.0">
                 <text strict="false">QThread(29ec6f0) finished ()</text>
                 <unsure/>
            </message>
        </function>
        <message type="Signal" level="verboses" qtmin="5.12.0" format="xml">
             <text strict="false">QThread(29ec6f0) finished ()</text>
             <unsure/>
             <unsure/>
             <unsure/>
        </message>
        <message type="Duration" format="xml">
             <text strict="false">0.00ms</text>
             <unsure/>
        </message>
        <unsure format="xunitxml" />
        <unsure level="verboses" format="xunitxml" qtmin="5.6.0" />
        <unsure level="verboses" format="xunitxml" qtmin="5.6.0" />
        <unsure level="verboses" format="xunitxml" qtmin="5.12.0" />
        <unsure level="verbose2" format="xunitxml" />
        <unsure level="verbose2" format="xunitxml" />
        <unsure level="silent" format="txt" />
        <unsure format="txt,xml,xunitxml" />
    </class>
    <class name="OneSubTest" type="Pass" format="lightxml">
        <unsure/>
        <unsure/>
        <unsure/>
        <unsure/>
        <magicfound/>
        <function name="initTestCase" type="Pass">
            <unsure/>
            <message type="Signal" level="verboses" qtmin="5.6.0">
                 <text strict="false">QThread(29ec6f0) started ()</text>
                 <unsure/>
                 <unsure/>
                 <unsure/>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
                 <unsure/>
            </message>
            <message type="Duration">
                 <text strict="false">0.00ms</text>
                 <unsure/>
            </message>
            <unsure/>
        </function>
        <function name="testPass" type="Pass">
            <unsure/>
            <message type="Info" level="verbose2" file="onepasstest.cpp" line="34">
                 <text strict="true">QVERIFY(true)</text>
                 <unsure/>
                 <unsure/>
                 <unsure/>
            </message>
            <message type="Pass">
                 <text strict="true">Test passed</text>
                 <unsure/>
            </message>
            <message type="Duration">
                 <text strict="false">0.00ms</text>
                 <unsure/>
            </message>
            <unsure/>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <unsure/>
            <message type="Pass">
                 <text strict="true">Test passed</text>
                 <unsure/>
            </message>
            <message type="Duration">
                 <text strict="false">0.00ms</text>
                 <unsure/>
            </message>
            <unsure/>
        </function>
        <message type="Signal" level="verboses" qtmin="5.12.0">
            <text strict="false">QThread(29ec6f0) finished ()</text>
            <unsure/>
            <unsure/>
            <unsure/>
        </message>
        <message type="Duration">
             <text strict="false">0.00ms</text>
             <unsure/>
        </message>
    </class>
</qtestliboutput>

=== pasccom/QTestLibPlugin/tests/qt5/MakefileSpaceTest/makefilespacetest.xml
<?xml version="1.0" ?>
<!-- Copyright 2016-2020 Pascal COMBES <pascom@orange.fr>
     
     This file is part of QTestLibPlugin.
     
     QTestLibPlugin is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     
     QTestLibPlugin is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
     GNU General Public License for more details.
     
     You should have received a copy of the GNU General Public License
     along with QTestLibPlugin. If not, see <http://www.gnu.org/licenses/>
-->

<!DOCTYPE qtestliboutput SYSTEM "../../qtestliboutput.dtd">
<qtestliboutput>
    <results format="xunitxml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
    </results>
    <results format="lightxml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
    </results>
    <results format="xml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
    </results>
    <results format="txt">
        <unsure/>
        <magicfound level="silent" />
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="silent" />
        <unsure/>
    </results>
    <class name="OnePassTest" type="Pass" format="!lightxml" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <function name="testPass" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Info" strict="true" level="verbose2" file="onepasstest.cpp" line="34">
                QVERIFY(true)
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <message type="Duration" strict="false" format="xml" >
            0.00ms
        </message>
    </class>
    <class name="OneSubTest" type="Pass" format="lightxml" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <function name="testPass" type="Pass">
            <message type="Info" strict="true" level="verbose2" file="onepasstest.cpp" line="34">
                QVERIFY(true)
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <message type="Duration" strict="false">
            0.00ms
        </message>
    </class>
</qtestliboutput>
